### PR TITLE
Add Romanian translations

### PR DESCRIPTION
**Pull request by brarcher**

### CODE REVIEW

**Comment by licaon-kter** [comment]
Why open PRs? Just merge it from Transifex and be done.

**Comment by brarcher** [comment]
Woah, is there a way to do that from transifex? I've not seen a way where transifex would submit a pull request, only where I can download the translated xml resources and do it myself. I've also seen that sometimes they are incorrectly formatted, where strings are incorrectly escaped such as:
```
<string name="cannotEncodeFile">Nu s-a putut coda fișierul: <xliff:g id=\"failure_description\">%s</xliff:g></string>
```
where the id in the xliff tag should not be escaped, but it is for some translations. (Perhaps the volunteer translators are adding those in). I end up need to correct them before pushing.

**Comment by brarcher** [comment]
I guess I did not look very hard. They do have some GitHub integrations. I'll need to look into that, as updating the translations right now is far from fun.

**Comment by licaon-kter** [comment]
Yes use that.

As for the xliff thing, I he no idea, it's an error right.

**Comment by brarcher** [comment]
@licaon-kter, I looked into Transifex's integrations. The best which would be usable by me is a python tool which will pull down the translations for a given project. Using this at least I would not need to do it manually, which I have gotten wrong before. 

I found that Transifex uses a different language and region code layout than Android. For example, Transifex uses "ro_RO" and Android uses "ro-rRO". There is also the quoting issue. To get around these, I ended up writing a [wrapper script](https://github.com/brarcher/tools/blob/master/transifex/transifex-pull) for the cli tool which fixing the translations after the fetch.

I'll still need to post pull requests with translation updates (as I'm not that interested in having Transifex push updates), but because the process is now much easier I'll be more likely to do so before a release.

FYI (:

**Comment by licaon-kter** [comment]
I saw that ro-rRo only on Conversations, others use ro-RO just fine, no idea why the change.

**Pull request merged**
